name: Artillery Socket.IO Load Test

on:
  push:
    branches:
      - main
      - lesson3
      - lesson3-pro
 
jobs:
  artillery:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run test/test-to-run-on-ci.yml --output ./report.json --name TestFromGithubActions --record --key API_KEY_ARTILLERY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: artillery-report
          path: ./report.json