name: Artillery Socket.IO Load Test

on:
  push:
    branches:
      - main
      - lesson3
 
jobs:
  artillery:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run tests/performance/socket-io.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: artillery-report
          path: ./report.json